class phoneCodes  {
    nameCode:string;
    code:string;
    id:Number;
    name:string;
}


export const countryCodes :Array<phoneCodes> = [
  { nameCode:"IN",  code: "91",name:"India",id:1 },
  { nameCode: "BD", code: "880",name:"Bangladesh",id:2 },
  { nameCode: "BE", code: "32",name:"Belgium" ,id:3 },
  { nameCode: "BF", code: "226" ,name:"Burkina Faso",id:4 },
  { nameCode: "BG", code: "359",name:"Bulgaria",id:5  },
  { nameCode: "BA", code: "387" ,name:"Bosnia and Herzegovina",id:6 },
  { nameCode: "BB", code: "+1-246",name:"Barbados",id:7  },
  { nameCode: "WF", code: "681",name:"Wallis and Futuna",id:8  },
  { nameCode: "BL", code: "590",name:"Saint Barthelemy",id:9  },
  { nameCode: "BM", code: "+1-441",name:"Bermuda" ,id:10 },
  { nameCode: "BN", code: "673",name:"Brunei",id:11  },
  { nameCode: "BO", code: "591",name:"Bolivia",id:12  },
  { nameCode: "BH", code: "973" ,name:"Bahrain",id:13 },
  {nameCode: "BI", code: "257",name:"Burundi",id:14 },
  {nameCode: "BJ", code: "975",name:"Benin",id:15 },
  {nameCode: "JM", code: "+1-876",name:"Jamaica" ,id:16},
  {nameCode: "BV", code: "",name:"Bouvet Island",id:17 },
  {nameCode: "BW", code: "267",name:"Botswana",id:18 },
  {nameCode: "WS", code: "685",name:"Samoa",id:19 },
  {nameCode: "BQ", code: "599",name:"Bonaire, Saint Eustatius and Saba",id:20 },
  {nameCode: "BR", code: "55",name:"Brazil" ,id:21},
  {nameCode: "BS", code: "+1-242",name:"Bahamas",id:22 },
  {nameCode: "JE", code: "+44-1534",name:"Jersey",id:23 },
  {nameCode: "BY", code: "375",name:"Belarus",id:24 },
  {nameCode: "BZ", code: "501",name:"Belize",id:25 },
  {nameCode: "RU", code: "7",name:"Russia",id:26},
  {nameCode: "RW", code: "250",name:"Rwanda",id:27 },
  {nameCode: "RS", code: "381",name:"Serbia" ,id:28},
  {nameCode: "TL", code: "670",name:"East Timor",id:29 },
  {nameCode: "RE", code: "262",name:"Reunion",id:30 },
  {nameCode: "TM", code: "993",name:"Turkmenistan",id:31 },
  {nameCode: "TJ", code: "992",name:"Tajikistan",id:32 },
  {nameCode: "RO", code: "40",name:"Romania",id:33 },
  {nameCode: "TK", code: "690",name:"Tokelau",id:34 },
  {nameCode: "GW", code: "245",name:"Guinea-Bissau",id:35 },
  {nameCode: "GU", code: "+1-671",name:"Guam",id:36 },
  {nameCode: "GT", code: "502",name:"Guatemala",id:37 },
  {nameCode: "GS", code: "",name:"South Georgia and the South Sandwich Islands",id:38 },
  {nameCode: "GR", code: "30",name:"Greece" ,id:39},
  {nameCode: "GQ", code: "240",name:"Equatorial Guinea",id:40 },
  {nameCode: "GP", code: "590",name:"Guadeloupe" ,id:41},
  {nameCode: "JP", code: "81",name:"Japan" ,id:42},
  {nameCode: "GY", code: "592",name:"Guyana",id:43 },
  {nameCode: "GG", code: "+44-1481",name:"Guernsey",id:44 },
  {nameCode: "GF", code: "594",name:"French Guiana",id:45 },
  {nameCode: "GE", code: "995",name:"Georgia",id:46 },
  {nameCode: "GD", code: "+1-473",name:"Grenada" ,id:47},
  {nameCode: "GB", code: "44",name:"United Kingdom",id:48 },
  {nameCode: "GA", code: "241",name:"Gabon" ,id:49},
  {nameCode: "SV", code: "503",name:"El Salvador",id:50 },
  {nameCode: "GN", code: "224",name:"Guinea",id:51 },
  {nameCode: "GM", code: "220",name:"Gambia",id:52 },
  {nameCode: "GL", code: "299",name:"Greenland",id:53},
  {nameCode: "GI", code: "350",name:"Gibraltar",id:54 },
  {nameCode: "GH", code: "233",name:"Ghana",id:55 },
  {nameCode: "OM", code: "968",name:"Oman",id:56 },
  {nameCode: "TN", code: "216",name:"Tunisia",id:57 },
  {nameCode: "JO", code: "962",name:"Jordan",id:58 },
  {nameCode: "HR", code: "385",name:"Croatia",id:59 },
  {nameCode: "HT", code: "509",name:"Haiti",id:60 },
  {nameCode: "HU", code: "36",name:"Hungary",id:61 },
  {nameCode: "HK", code: "852",name:"Hong Kong",id:62 },
  {nameCode: "HN", code: "504",name:"Honduras",id:63 },
  {nameCode: "HM", code: "",name:"Heard Island and McDonald Islands",id:64 },
  {nameCode: "VE", code: "58",name:"Venezuela",id:65 },
  {nameCode: "PR", code: "+1-787 and 1-939",name:"Puerto Rico",id:66 },
  {nameCode: "PS", code: "970",name:"Palestinian Territory",id:67 },
  {nameCode: "PW", code: "680",name:"Palau",id:68 },
  {nameCode: "PT", code: "351",name:"Portugal",id:69 },
  {nameCode: "SJ", code: "47",name:"Svalbard and Jan Mayen",id:70 },
  {nameCode: "PY", code: "595",name:"Paraguay",id:71 },
  {nameCode: "IQ", code: "964",name:"Iraq",id:72 },
  {nameCode: "PA", code: "507",name:"Panama",id:73 },
  {nameCode: "PF", code: "689",name:"French Polynesia",id:74 },
  {nameCode: "PG", code: "675",name:"Papua New Guinea",id:75 },
  {nameCode: "PE", code: "51",name:"Peru",id:76 },
  {nameCode: "PK", code: "92",name:"Pakistan",id:77 },
  {nameCode: "PH", code: "63",name:"Philippines",id:78 },
  {nameCode: "PN", code: "870",name:"Pitcairn",id:79 },
  {nameCode: "PL", code: "48",name:"Poland",id:80},
  {nameCode: "PM", code: "508",name:"Saint Pierre and Miquelon",id:81 },
  {nameCode: "ZM", code: "260",name:"Zambia",id:82 },
  {nameCode: "EH", code: "212 ",name:"Western Sahara",id:83 },
  {nameCode: "EE", code: "372",name:"Estonia",id:84 },
  {nameCode: "EG", code: "20",name:"Egypt",id:85},
  {nameCode: "ZA", code: "27",name:"South Africa",id:86 },
  {nameCode: "EC", code: "593",name:"Ecuador",id:87 },
  {nameCode: "IT", code: "39",name:"Italy",id:88 },
  {nameCode: "VN", code: "84",name:"Vietnam",id:89 },
  {nameCode: "SB", code: "677",name:"Solomon Islands",id:90 },
  {nameCode: "ET", code: "251",name:"Ethiopia",id:91 },
  {nameCode: "SO", code: "252",name:"Somalia",id:92 },
  {nameCode: "ZW", code: "263",name:"Zimbabwe",id:93 },
  {nameCode: "SA", code: "966",name:"Saudi Arabia" ,id:94},
  {nameCode:"ES" ,code: "34",name:"Spain",id:95 }, 
  {nameCode:"ER",code: "291",name:"Eritrea",id:96 },
  {nameCode:"MD",code: "373",name:"Moldova" ,id:97},
  {nameCode: "MG",code: "261",name:"Madagascar",id:98 },
  {nameCode: "MF",code: "590",name:"Saint Martin",id:99 },
  {nameCode: "MA",code: "212",name:"Morocco",id:100},
  {nameCode:"MC",code: "377",name:"Monaco",id:101 },
  {nameCode:"UZ",code: "998",name:"Uzbekistan",id:102 },
  {nameCode: "MM",code: "95",name:"Myanmar",id:103 },
  {nameCode:"ML",code: "223",name:"Mali",id:104 },
  {nameCode:"MO",code: "853",name:"Macao",id:105 }, 
  {nameCode:"MN",code: "976",name:"Mongolia",id:106 },
  {nameCode:"MH",code: "692",name:"Marshall Islands",id:107 },
  {nameCode:"MK",code: "389",name:"Macedonia",id:108 },
  {nameCode:"MU",code: "230",name:"Mauritius",id:109 },
  {nameCode:"MT",code: "356",name:"Malta",id:110},
  {nameCode: "MW",code: "265",name:"Malawi",id:111 },
  {nameCode: "MV",code: "960",name:"Maldives",id:112 },
  {nameCode:"MQ",code: "596",name:"Martinique",id:113 },
  {nameCode:"MP",code: "+1-670",name:"Northern Mariana Islands" ,id:114},
  {nameCode: "MS",code: "+1-664",name:"Montserrat" ,id:115},
  {nameCode:"MR",code: "222",name:"Mauritania",id:116 },
  {nameCode:"IM",code: "+44-1624",name:"Isle of Man" ,id:117},
  {nameCode:"UG",code: "256",name:"Uganda" ,id:118},
  {nameCode:"TZ",code: "255",name:"Tanzania" ,id:119},
  {nameCode:"MY",code: "60",name:"Malaysia",id:120 },
  {nameCode:"MX",code: "52",name:"Mexico",id:121 },
  {nameCode: "IL",code: "972",name:"Israel" ,id:122},
  {nameCode:"FR",code: "33",name:"France",id:123 },
  {nameCode:"IO",code: "246",name:"British Indian Ocean Territory",id:124 },
  {nameCode:"SH",code: "290",name:"Saint Helena",id:125 },
  {nameCode:"FI",code: "358",name:"Finland",id:126 },
  {nameCode:"FJ",code: "679",name:"Fiji" ,id:127},
  {nameCode:"FK",code: "500",name:"Falkland Islands",id:128 },
  {nameCode:"FM",code: "691",name:"Micronesia",id:129 },
  {nameCode:"FO",code: "298",name:"Faroe Islands",id:130 },
  {nameCode: "NI",code: "505",name:"Nicaragua",id:131 },
  {nameCode: "NL",code: "31",name:"Netherlands",id:132 },
  {nameCode: "NO",code: "47",name:"Norway",id:133 },
  {nameCode: "NA",code: "264",name:"Namibia",id:134 },
  {nameCode: "VU",code: "678",name:"Vanuatu",id:135 },
  {nameCode: "NC",code: "687",name:"New Caledonia",id:136 },
  {nameCode: "NE",code: "227",name:"Niger",id:137 },
  {nameCode: "NF",code: "672",name:"Norfolk Island",id:138 },
  {nameCode: "NG",code: "234",name:"Nigeria",id:139 },
  {nameCode: "NZ",code: "64",name:"New Zealand",id:140 },
  {nameCode: "NP",code: "977",name:"Nepal",id:141 },
  {nameCode: "NR",code: "674",name:"Nauru",id:142 }, 
  {nameCode:"NU",code: "683",name:"Niue",id:143 }, 
  {nameCode:"CK",code: "682",name:"Cook Islands",id:144 },
  {nameCode: "XK",code: "",name:"Kosovo",id:145 }, 
  {nameCode:"CI",code: "225",name:"Ivory Coast",id:146 },
  {nameCode: "CH",code: "41",name:"Switzerland",id:147 }, 
  {nameCode:"CO",code: "57",name:"Colombia" ,id:148}, 
  {nameCode:"CN",code: "86",name:"China",id:149 },
  {nameCode: "CM",code: "237",name:"Cameroon",id:150 },
  {nameCode: "CL",code: "56",name:"Chile",id:151 },
  {nameCode: "CC",code: "61",name:"Cocos Islands",id:152 },
  {nameCode: "CA",code: "1",name:"Canada",id:153 },
  {nameCode: "CG",code: "242",name:"Republic of the Congo",id:154 },
  {nameCode: "CF",code: "236",name:"Central African Republic",id:155 },
  {nameCode: "CD",code: "243",name:"Democratic Republic of the Congo",id:156 },
  {nameCode: "CZ",code: "420",name:"Czech Republic" ,id:157}, 
  {nameCode:"CY",code: "357",name:"Cyprus",id:158 },
  {nameCode: "CX",code: "61",name:"Christmas Island",id:159 },
  {nameCode: "CR",code: "506",name:"Costa Rica",id:160 },
  {nameCode: "CW",code: "599",name:"Curacao",id:161 },
  {nameCode: "CV",code: "238",name:"Cape Verde",id:162 },
  {nameCode: "CU",code: "53",name:"Cuba",id:163 }, 
  {nameCode:"SZ",code: "268",name:"Swaziland",id:164 }, 
  {nameCode:"SY",code: "963",name:"Syria",id:165 },
  {nameCode: "SX",code: "599",name:"Sint Maarten",id:166 },
  {nameCode: "KG",code: "996",name:"Kyrgyzstan",id:167 }, 
  {nameCode:"KE",code: "254",name:"Kenya",id:168 },
  {nameCode: "SS",code: "211",name:"South Sudan",id:169 },
  {nameCode: "SR",code: "597",name:"Suriname",id:170 },
  {nameCode: "KI",code: "686",name:"Kiribati" ,id:171},
  {nameCode: "KH",code: "855",name:"Cambodia" ,id:172},
  {nameCode: "KN",code: "+1-869",name:"Saint Kitts and Nevis",id:173 }, 
  {nameCode:"KM",code: "269",name:"Comoros",id:174 },
  {nameCode: "ST",code: "239",name:"Sao Tome and Principe",id:175 },
  {nameCode: "SK",code: "421",name:"Slovakia",id:176 },
  {nameCode: "KR",code: "82",name:"South Korea" ,id:177},
  {nameCode: "SI",code: "386",name:"Slovenia" ,id:178}, 
  {nameCode:"KP",code: "850",name:"North Korea",id:179 }, 
  {nameCode:"KW",code: "965",name:"Kuwait",id:180 },
  {nameCode: "SN",code: "221",name:"Senegal",id:181 }, 
  {nameCode:"SM",code: "378",name:"San Marino",id:182 },
  {nameCode: "SL",code: "232",name:"Sierra Leone",id:183 }, 
  {nameCode:"SC",code: "248",name:"Seychelles",id:184 }, 
  {nameCode:"KZ",code: "7",name:"Kazakhstan",id:185 },
  {nameCode: "KY",code: "+1-345",name:"Cayman Islands" ,id:186}, 
  {nameCode:"SG",code: "65",name:"Singapore" ,id:187}, 
  {nameCode:"SE",code: "46",name:"Sweden" ,id:188}, 
  {nameCode:"SD",code: "249",name:"Sudan",id:189 }, 
  {nameCode:"DO",code: "+1-809 and 1-829",name:"Dominican Republic",id:190},
  {nameCode: "DM",code: "+1-767",name:"Dominica",id:191 }, 
  {nameCode:"DJ",code: "253",name:"Djibouti",id:192 },
  {nameCode: "DK",code: "45",name:"Denmark" ,id:193},
  {nameCode: "VG",code: "+1-284",name:"British Virgin Islands",id:194 },
  {nameCode: "DE",code: "49",name:"Germany",id:195 },
  {nameCode: "YE",code: "967",name:"Yemen",id:196 }, 
  {nameCode:"DZ",code: "213",name:"Algeria",id:197 }, 
  {nameCode:"US",code: "1",name:"United States",id:198 }, 
  {nameCode:"UY",code: "598",name:"Uruguay",id:199 }, 
  {nameCode:"YT",code: "262",name:"Mayotte",id:200 }, 
  {nameCode:"UM",code: "1",name:"United States Minor Outlying Islands",id:201 },
  {nameCode: "LB",code: "961",name:"Lebanon",id:202 },
  {nameCode: "LC",code: "+1-758",name:"Saint Lucia",id:203 }, 
  {nameCode:"LA",code: "856",name:"Laos",id:204 }, 
  {nameCode:"TV",code: "688",name:"Tuvalu",id:205 }, 
  {nameCode:"TW",code: "886",name:"Taiwan",id:206 },
  {nameCode: "TT",code: "+1-868",name:"Trinidad and Tobago",id:207 }, 
  {nameCode:"TR",code: "90",name:"Turkey",id:208 }, 
  {nameCode:"LK",code: "94",name:"Sri Lanka",id:209 }, 
  {nameCode:"LI",code: "423",name:"Liechtenstein",id:210 }, 
  {nameCode:"LV",code: "371",name:"Latvia",id:211 }, 
  {nameCode:"TO",code: "676",name:"Tonga",id:212 }, 
  {nameCode:"LT",code: "370",name:"Lithuania",id:213 },
  {nameCode: "LU",code: "352",name:"Luxembourg",id:214 },
  {nameCode: "LR",code: "231",name:"Liberia",id:215 }, 
  {nameCode:"LS",code: "266",name:"Lesotho",id:216 }, 
  {nameCode:"TH",code: "66",name:"Thailand",id:217 },
  {nameCode: "TF",code: "",name:"French Southern Territories",id:218 },
  {nameCode: "TG",code: "228",name:"Togo",id:219 },
  {nameCode: "TD",code: "235",name:"Chad",id:220 },
  {nameCode: "TC",code: "+1-649",name:"Turks and Caicos Islands",id:221 },
  {nameCode: "LY",code: "218",name:"Libya",id:222 }, 
  {nameCode:"VA",code: "379",name:"Vatican" ,id:223},
  {nameCode:"VC",code: "+1-784",name:"Saint Vincent and the Grenadines",id:224 },
  {nameCode:"AE",code: "971",name:"United Arab Emirates",id:225 },
  {nameCode:"AD",code: "376",name:"Andorra",id:226 },
  {nameCode:"AG",code: "+1-268",name:"Antigua and Barbuda",id:227 },
  {nameCode: "AF",code: "93",name:"Afghanistan",id:228 },
  {nameCode:"AI",code: "+1-264",name:"Anguilla",id:229 },
  {nameCode:"VI",code: "+1-340",name:"U.S. Virgin Islands",id:230 },
  {nameCode:"IS",code: "354",name:"Iceland",id:231 },
  {nameCode:"IR",code: "98",name:"Iran",id:232 },
  {nameCode: "AM",code: "374",name:"Armenia",id:233 },
  {nameCode: "AL",code: "355",name:"Albania",id:234 },
  {nameCode:"AO",code: "244",name:"Angola" ,id:235},
  {nameCode:"AQ",code: "",name:"Antarctica",id:236 },
  {nameCode:"AS",code: "+1-684",name:"American Samoa",id:237 },
  {nameCode:"AR",code: "54",name:"Argentina",id:238 },
  {nameCode: "AU",code: "61",name:"Australia",id:239 },
  {nameCode:"AT",code: "43",name:"Austria",id:240 },
  {nameCode:"AW",code: "297",name:"Aruba",id:241 },
  {nameCode:"AX",code: "+358-18",name:"Aland Islands",id:242 },
  {nameCode: "AZ",code: "994",name:"Azerbaijan",id:243 },
  {nameCode: "IE",code: "353",name:"Ireland",id:244 },
  {nameCode:"ID",code: "62",name:"Indonesia",id:245 },
  {nameCode:"UA",code: "380",name:"Ukraine",id:246 },
  {nameCode:"QA",code: "974",name:"Qatar",id:247 },
  {nameCode: "MZ",code: "258",name:"Mozambique",id:248 }
]

